#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate


echo "Copying $OPENSHIFT_REPO_DIR/configs/openshift/settings.py to $OPENSHIFT_REPO_DIR/okota_website"
cp "$OPENSHIFT_REPO_DIR"configs/openshift/settings.py "$OPENSHIFT_REPO_DIR"okota_website

echo "Copying $OPENSHIFT_REPO_DIR/configs/openshift/wsgi.py to $OPENSHIFT_REPO_DIR"
cp "$OPENSHIFT_REPO_DIR"configs/openshift/wsgi.py $OPENSHIFT_REPO_DIR